[package]
name = "quark-ai"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
crossbeam-channel.workspace = true
thiserror.workspace = true
tracing.workspace = true
ureq.workspace = true
